export const POPULATE_DATA = "POPULATE_DATA";
export const SAVE_STORAGE = "SAVE_STORAGE";
export const REMOVE_STORAGE = "REMOVE_STORAGE";
export const DISPLAY_POPUP = "DISPLAY_POPUP";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
